

THE20 = {'ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLN',
         'GLU', 'GLY', 'HIS', 'ILE', 'LEU', 'LYS',
         'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP',
         'TYR', 'VAL'}

BB_ATOMS = ['C', 'CA', 'N', 'O']
BB_ATOMS_PLUS_CB = ['C', 'CA', 'N', 'O', 'CB']
SET_BB_ATOMS = set(BB_ATOMS)
SET_BB_ATOMS_PLUS_CB = set(BB_ATOMS_PLUS_CB)

SIDE_CHAINS = {'MET': ['CB', 'CE', 'CG', 'SD'],
               'ILE': ['CB', 'CD1', 'CG1', 'CG2'],
               'LEU': ['CB', 'CD1', 'CD2', 'CG'],
               'VAL': ['CB', 'CG1', 'CG2'],
               'THR': ['CB', 'CG2', 'OG1'],
               'GLY': [],
               'ALA': ['CB'],
               'ARG': ['CB', 'CD', 'CG', 'CZ', 'NE', 'NH1', 'NH2'],
               'SER': ['CB', 'OG'],
               'LYS': ['CB', 'CD', 'CE', 'CG', 'NZ'],
               'HIS': ['CB', 'CD2', 'CE1', 'CG', 'ND1', 'NE2'],
               'GLU': ['CB', 'CD', 'CG', 'OE1', 'OE2'],
               'ASP': ['CB', 'CG', 'OD1', 'OD2'],
               'PRO': ['CB', 'CD', 'CG'],
               'GLN': ['CB', 'CD', 'CG', 'NE2', 'OE1'],
               'TYR': ['CB', 'CD1', 'CD2', 'CE1', 'CE2', 'CG', 'CZ', 'OH'],
               'TRP': ['CB', 'CD1', 'CD2', 'CE2', 'CE3', 'CG', 'CH2', 'CZ2', 'CZ3', 'NE1'],
               'CYS': ['CB', 'SG'],
               'ASN': ['CB', 'CG', 'ND2', 'OD1'],
               'PHE': ['CB', 'CD1', 'CD2', 'CE1', 'CE2', 'CG', 'CZ']}

CHI_ANGLES = {
    'ARG' : [['N','CA','CB','CG'], ['CA','CB','CG','CD'], ['CB','CG','CD','NE'], ['CG','CD','NE','CZ']], #, ['CD','NE','CZ','NH1']],
    'ASN' : [['N','CA','CB','CG'], ['CA','CB','CG','OD1']],
    'ASP' : [['N','CA','CB','CG'], ['CA','CB','CG','OD1']],
    'CYS' : [['N','CA','CB','SG']],
    'GLN' : [['N','CA','CB','CG'], ['CA','CB','CG','CD'], ['CB','CG','CD','OE1']],
    'GLU' : [['N','CA','CB','CG'], ['CA','CB','CG','CD'], ['CB','CG','CD','OE1']],
    'HIS' : [['N','CA','CB','CG'], ['CA', 'CB','CG','ND1']],
    'ILE' : [['N','CA','CB','CG1'], ['CA','CB','CG1','CD1']],
    'LEU' : [['N','CA','CB','CG'], ['CA','CB','CG','CD1']],
    'LYS' : [['N','CA','CB','CG'], ['CA','CB','CG','CD'], ['CB','CG','CD','CE'], ['CG','CD','CE','NZ']],
    'MET' : [['N','CA','CB','CG'], ['CA','CB','CG','SD'], ['CB','CG','SD','CE']],
    'PHE' : [['N','CA','CB','CG'], ['CA','CB','CG','CD1']],
    'PRO' : [['N','CA','CB','CG'], ['CA','CB','CG','CD']],
    'SER' : [['N','CA','CB','OG']],
    'THR' : [['N','CA','CB','OG1']],
    'TRP' : [['N','CA','CB','CG'], ['CA','CB','CG','CD1']],
    'TYR' : [['N','CA','CB','CG'], ['CA','CB','CG','CD1']],
    'VAL' : [['N','CA','CB','CG1']]
}

RELATED_DIHEDRALS = {
    'ALA' : [('N:CA:C:O', 'O:C:CA:CB')],
    'ARG' : [('N:CA:C:O', 'O:C:CA:CB')],
    'ASN' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:ND2')],
    'ASP' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:OD2')],
    'CYS' : [('N:CA:C:O', 'O:C:CA:CB')],
    'GLN' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi3', 'CB:CG:CD:NE2')],
    'GLU' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi3', 'CB:CG:CD:OE2')],
    'HIS' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:CD2')],
    'ILE' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi1', 'N:CA:CB:CG2')],
    'LEU' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:CD2')],
    'LYS' : [('N:CA:C:O', 'O:C:CA:CB')],
    'MET' : [('N:CA:C:O', 'O:C:CA:CB')],
    'PHE' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:CD2')],
    'PRO' : [('N:CA:C:O', 'O:C:CA:CB')],
    'SER' : [('N:CA:C:O', 'O:C:CA:CB')],
    'THR' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi1', 'N:CA:CB:CG2')],
    'TRP' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:CD2')],
    'TYR' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi2', 'CA:CB:CG:CD2')],
    'VAL' : [('N:CA:C:O', 'O:C:CA:CB'), ('chi1', 'N:CA:CB:CG2')],
}
DESIRED_DIHEDRAL_TO_REFERENCE_DIHEDRAL = {resname: {pair[1]: pair[0] for pair in RELATED_DIHEDRALS[resname]} for resname in RELATED_DIHEDRALS}

PEPTIDE_BOND = ("C", "N")

INTRA_RES_BONDS = dict(
    ALA={("CA", "N"), ("C", "O"), ("C", "CA"), ("CA", "CB")},
    ARG={
        ("CA", "N"),
        ("CD", "NE"),
        ("CA", "CB"),
        ("CZ", "NH1"),
        ("CB", "CG"),
        ("CD", "CG"),
        ("C", "CA"),
        ("CZ", "NE"),
        ("CZ", "NH2"),
        ("C", "O"),
    },
    ASN={
        ("CA", "N"),
        ("CB", "CG"),
        ("CG", "OD1"),
        ("C", "CA"),
        ("CG", "ND2"),
        ("C", "O"),
        ("CA", "CB"),
    },
    ASP={
        ("CA", "N"),
        ("CG", "OD1"),
        ("CB", "CG"),
        ("C", "CA"),
        ("CA", "CB"),
        ("C", "O"),
        ("CG", "OD2"),
    },
    CYS={("CA", "N"), ("CB", "SG"), ("C", "CA"), ("CA", "CB"), ("C", "O")},
    GLN={
        ("CA", "N"),
        ("CB", "CG"),
        ("CD", "NE2"),
        ("CD", "CG"),
        ("CD", "OE1"),
        ("C", "CA"),
        ("CA", "CB"),
        ("C", "O"),
    },
    GLU={
        ("CA", "N"),
        ("CD", "OE2"),
        ("CD", "CG"),
        ("CD", "OE1"),
        ("CB", "CG"),
        ("C", "CA"),
        ("CA", "CB"),
        ("C", "O"),
    },
    GLY={("CA", "N"), ("C", "O"), ("C", "CA")},
    HIS={
        ("CA", "N"),
        ("CG", "ND1"),
        ("CD2", "NE2"),
        ("CE1", "NE2"),
        ("CE1", "ND1"),
        ("C", "CA"),
        ("CD2", "CG"),
        ("CA", "CB"),
        ("C", "O"),
        ("CB", "CG"),
    },
    ILE={
        ("CA", "N"),
        ("CA", "CB"),
        ("CB", "CG1"),
        ("CB", "CG2"),
        ("C", "CA"),
        ("CD1", "CG1"),
        ("C", "O"),
    },
    LEU={
        ("CD1", "CG"),
        ("CA", "N"),
        ("CB", "CG"),
        ("C", "O"),
        ("CD2", "CG"),
        ("C", "CA"),
        ("CA", "CB"),
    },
    LYS={
        ("CA", "N"),
        ("CD", "CG"),
        ("CD", "CE"),
        ("CB", "CG"),
        ("C", "CA"),
        ("CA", "CB"),
        ("C", "O"),
        ("CE", "NZ"),
    },
    MET={
        ("CG", "SD"),
        ("CA", "N"),
        ("CB", "CG"),
        ("CE", "SD"),
        ("C", "CA"),
        ("CA", "CB"),
        ("C", "O"),
    },
    PHE={
        ("CE1", "CZ"),
        ("CA", "N"),
        ("CD1", "CG"),
        ("CD2", "CE2"),
        ("CB", "CG"),
        ("CD2", "CG"),
        ("CE2", "CZ"),
        ("C", "CA"),
        ("CD1", "CE1"),
        ("CA", "CB"),
        ("C", "O"),
    },
    PRO={
        ("CA", "N"),
        ("CB", "CG"),
        ("C", "CA"),
        ("CA", "CB"),
        ("C", "O"),
        ("CD", "CG"),
        ("CD", "N"),
    },
    SER={("CA", "N"), ("C", "CA"), ("CB", "OG"), ("C", "O"), ("CA", "CB")},
    THR={
        ("CA", "N"),
        ("CA", "CB"),
        ("CB", "OG1"),
        ("CB", "CG2"),
        ("C", "CA"),
        ("C", "O"),
    },
    TRP={
        ("CA", "N"),
        ("CD2", "CE2"),
        ("CE3", "CZ3"),
        ("CB", "CG"),
        ("CD2", "CG"),
        ("CD2", "CE3"),
        ("CH2", "CZ3"),
        ("CD1", "NE1"),
        ("C", "CA"),
        ("CE2", "CZ2"),
        ("CA", "CB"),
        ("C", "O"),
        ("CE2", "NE1"),
        ("CD1", "CG"),
        ("CH2", "CZ2"),
    },
    TYR={
        ("CB", "CG"),
        ("CA", "N"),
        ("CD1", "CG"),
        ("CD2", "CE2"),
        ("CD2", "CG"),
        ("CE2", "CZ"),
        ("CE1", "CZ"),
        ("C", "CA"),
        ("CD1", "CE1"),
        ("CA", "CB"),
        ("CZ", "OH"),
        ("C", "O"),
    },
    VAL={
        ("CA", "N"),
        ("CA", "CB"),
        ("C", "O"),
        ("CB", "CG2"),
        ("C", "CA"),
        ("CB", "CG1"),
    },
)

INTRA_RES_BONDS_TABLE = {}
for resname in INTRA_RES_BONDS:
    INTRA_RES_BONDS_TABLE[resname] = {}
    for atom1, atom2 in INTRA_RES_BONDS[resname]:
        INTRA_RES_BONDS_TABLE[resname][atom1] = atom2
        INTRA_RES_BONDS_TABLE[resname][atom2] = atom1